/**
 * Auto-generated by scripts/sync-deployments.mjs — do not edit by hand.
 * Source: reference/swap-vm/deployments/aqua-prime-fork.json
 */
import { aquaPrimeGatewayAbi, erc20Abi, wethAbi, faucetTokenAbi } from "./abis";

export type ContractName = "AquaPrimeSwapGateway" | "WETH" | "USDC";

const deployedContracts = {
  31337: {
    AquaPrimeSwapGateway: {
      address: "0x7412146614E0A583849378d7D9B08476aFb4Aa8B",
      abi: aquaPrimeGatewayAbi,
    },
    WETH: {
      address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
      abi: wethAbi,
    },
    USDC: {
      address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      abi: erc20Abi,
    },
  },
} as const;

export default deployedContracts;
