/**
 * Auto-generated by scripts/sync-deployments.mjs — do not edit by hand.
 */
export const primeDeskManifest = {
  chainId: 31337,
  blockNumber: 25605188,
  rpcUrl: "http://127.0.0.1:8545",
  maker: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266" as const,
  aqua: "0x4a055AA172C98ec32de118B9B5b6AC8B4099A580" as const,
  swapVMRouter: "0x5189A8e6dce42f5722813A95C18f0d914F76a7b2" as const,
  primeSelector: "0x677543959F35E998ADE4f7Eb6bCa19eCCFB27DA1" as const,
  gateway: "0x7412146614E0A583849378d7D9B08476aFb4Aa8B" as const,
  weth: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2" as const,
  usdc: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48" as const,
  baseToken: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2" as const,
  quoteToken: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48" as const,
  chainlinkEthUsd: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419" as const,
  ensName: "maker.primedesk.eth" as const,
  jarvisEns: "jarvis.primedesk.eth" as const,
  subgraphUrl: "",
  sampleQuoteOut1Eth: 1870536729,
  mintable: false,
  deployed: true,
} as const;

/** @deprecated use primeDeskManifest */
export const aquaPrimeManifest = primeDeskManifest;
